# Generated by Django 5.2.3 on 2025-07-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': ' فعالية', 'verbose_name_plural': ' الفعاليات'},
        ),
    ]
