# Generated by Django 5.2.3 on 2025-07-16 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.category', verbose_name='الفئات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
