# Generated by Django 5.2.3 on 2025-07-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_category_event_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='quantity',
            field=models.IntegerField(verbose_name='عدد الاماكن'),
        ),
    ]
