# Generated by Django 5.2.3 on 2025-07-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_is_private_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='address_ar',
            field=models.CharField(default=1, max_length=255, verbose_name='عنوان الفعالية بالعربي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='address_en',
            field=models.CharField(default=1, max_length=255, verbose_name='عنوان الفعالية بالإنجليزي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description_ar',
            field=models.TextField(default=1, verbose_name='الوصف بالعربي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(default=1, verbose_name='الوصف بالإنجليزي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title_ar',
            field=models.CharField(default=1, max_length=255, verbose_name='العنوان بالعربي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(default=1, max_length=255, verbose_name='العنوان بالإنجليزي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='طريقة التواصل'),
        ),
        migrations.AlterField(
            model_name='event',
            name='quantity',
            field=models.IntegerField(verbose_name='عدد الأماكن'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=15, verbose_name='حالة الفعالية'),
        ),
    ]
