# Generated by Django 5.2.3 on 2025-07-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_event_description_remove_event_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='quantity',
            new_name='tickets',
        ),
    ]
