# Generated by Django 5.2.3 on 2025-07-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_rename_quantity_event_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(default=1, max_length=255, verbose_name='الفئة بالعربي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default=1, max_length=255, verbose_name='الفئات بالانجليزي'),
            preserve_default=False,
        ),
    ]
