# Generated by Django 5.2.3 on 2025-07-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_images_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
