# Generated by Django 5.2.3 on 2025-07-09 12:52

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_images_delete_newsimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='images',
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news')),
            ],
        ),
    ]
