# Generated by Django 5.2.3 on 2025-07-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_images_alter_news_date_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
