# Generated by Django 5.2.3 on 2025-07-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': ' خبر', 'verbose_name_plural': ' الأخبار'},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name': ' صورة الخبر', 'verbose_name_plural': ' صور الخبر'},
        ),
    ]
