# Generated by Django 5.2.3 on 2025-07-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_quantity'),
        ('news', '0007_alter_news_options_alter_newsimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(to='events.category', verbose_name='الفئات'),
        ),
    ]
