# Generated by Django 5.2.3 on 2025-07-19 11:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='description_ar',
            field=models.TextField(default=1, verbose_name='الوصف بالعربي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(default=1, verbose_name='الوصف بالإنجليزي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title_ar',
            field=models.CharField(default=1, max_length=255, verbose_name='العنوان بالعربي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(default=1, max_length=255, verbose_name='العنوان بالإنجليزي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='صورة الخبر'),
        ),
    ]
