# Generated by Django 5.2.3 on 2025-07-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activities',
            name='status',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
