# Generated by Django 5.2.3 on 2025-07-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activities_is_private_activities_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=15),
        ),
    ]
