# Generated by Django 5.2.3 on 2025-07-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activities_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='quantity',
            new_name='tickets',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='title',
        ),
        migrations.AddField(
            model_name='activities',
            name='address_ar',
            field=models.CharField(default=1, max_length=255, verbose_name='عنوان النشاط بالعربي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activities',
            name='address_en',
            field=models.CharField(default=1, max_length=255, verbose_name='عنوان النشاط بالانجليزي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activities',
            name='description_ar',
            field=models.TextField(default=1, verbose_name='الوصف بالعربي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activities',
            name='description_en',
            field=models.TextField(default=1, verbose_name='الوصف بالانجليزي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activities',
            name='title_ar',
            field=models.CharField(default=1, max_length=255, verbose_name='العنوان بالعربي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activities',
            name='title_en',
            field=models.CharField(default=1, max_length=255, verbose_name='العنوان بالانجليزي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activities',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='طريقة التواصل'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=15, verbose_name='حالة النشاط'),
        ),
    ]
