# Generated by Django 5.2.3 on 2025-07-08 13:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_branch_alter_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'مستخدم'), ('team_head', 'رئيس الفريق'), ('team_hand', 'مساعد رئيس الفريق'), ('governorate_head', 'منسق المحافظة'), ('governorate_hand', 'مساعد منسق المحافظة'), ('department_head', 'منسق لجنة'), ('department_hand', 'مساعد منسق لجنة'), ('branch_head', 'منسق فرقة'), ('branch_hand', 'مساعد منسق قرقة'), ('branch_member', 'عضو')], default='user', max_length=32),
        ),
    ]
