# Generated by Django 5.2.3 on 2025-07-09 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_image_alter_user_password_alter_user_role'),
        ('structure', '0004_alter_governorate_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AlterField(
            model_name='user',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='structure.governorate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('board_head', 'رئيس المجلس'), ('board_vice', 'نائب رئيس المجلس'), ('central_unit_head', 'رئيس وحدة مركزية'), ('central_unit_vice', 'نائب رئيس وحدة مركزية'), ('governorate_head', 'منسق محافظة'), ('governorate_vice', 'نائب منسق محافظة'), ('local_unit_head', 'رئيس وحدة محلية'), ('local_unit_vice', 'نائب رئيس وحدة محلية'), ('local_unit_member', 'عضو وحدة محلية')], max_length=32),
        ),
    ]
