# Generated by Django 5.2.3 on 2025-07-09 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_branch_remove_user_department_and_more'),
        ('structure', '0005_remove_department_governorate_remove_department_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='central_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centeralunit', to='structure.centralunit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governrate', to='structure.governorate'),
        ),
    ]
