# Generated by Django 5.2.3 on 2025-07-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_central_unit_alter_user_governorate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('board_head', 'رئيس المجلس'), ('board_vice', 'نائب رئيس المجلس'), ('central_unit_head', 'رئيس وحدة مركزية'), ('central_unit_vice', 'نائب رئيس وحدة مركزية'), ('governorate_head', 'منسق محافظة'), ('governorate_vice', 'نائب منسق محافظة'), ('local_unit_head', 'رئيس وحدة محلية'), ('local_unit_vice', 'نائب رئيس وحدة محلية'), ('unit_member', 'عضو وحدة')], max_length=32),
        ),
    ]
