# Generated by Django 5.2.3 on 2025-07-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستحدمين'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('board_head', 'رئيس المجلس'), ('board_vice', 'نائب رئيس المجلس'), ('central_unit_head', 'رئيس وحدة مركزية'), ('central_unit_vice', 'نائب رئيس وحدة مركزية'), ('governorate_head', 'منسق محافظة'), ('governorate_vice', 'نائب منسق محافظة'), ('local_unit_head', 'رئيس وحدة محلية'), ('local_unit_vice', 'نائب رئيس وحدة محلية'), ('unit_member', 'عضو وحدة')], max_length=50, verbose_name='الدور'),
        ),
    ]
