# Generated by Django 5.2.3 on 2025-07-10 15:26

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_options_alter_user_email_and_more'),
        ('structure', '0010_rename_deputy_centralunit_vice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='central_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centeralunit', to='structure.centralunit', verbose_name='الوحدة المركزية'),
        ),
        migrations.AlterField(
            model_name='user',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governrate', to='structure.governorate', verbose_name='المحافظه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('board_head', 'رئيس المجلس'), ('board_vice', 'نائب رئيس المجلس'), ('central_unit_head', 'رئيس وحدة مركزية'), ('central_unit_vice', 'نائب رئيس وحدة مركزية'), ('governorate_head', 'منسق محافظة'), ('governorate_vice', 'نائب منسق محافظة'), ('unit_member', 'عضو وحدة')], max_length=50, verbose_name='الدور'),
        ),
    ]
