# Generated by Django 5.2.3 on 2025-07-10 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_central_unit_alter_user_governorate_and_more'),
        ('structure', '0010_rename_deputy_centralunit_vice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governrate', to='structure.governorate', verbose_name='المحافظة'),
        ),
    ]
