# Generated by Django 5.2.3 on 2025-07-17 13:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_back',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة بطاقة الرقم القومي من الخلف'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_front',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة بطاقة الرقم القومي من الامام'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(default=1, max_length=14, verbose_name='الرقم القومي'),
            preserve_default=False,
        ),
    ]
