# Generated by Django 5.2.3 on 2025-07-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_id_back_user_id_front_user_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='الرقم القومي'),
        ),
    ]
