# Generated by Django 5.2.3 on 2025-07-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('central_unit_head', 'رئيس وحدة مركزية'), ('central_unit_vice', 'نائب رئيس وحدة مركزية'), ('governorate_head', 'منسق محافظة'), ('governorate_vice', 'نائب منسق محافظة'), ('unit_member', 'عضو وحدة'), ('user', 'مستخدم')], default='user', max_length=50, verbose_name='الدور'),
        ),
    ]
