# Generated by Django 5.2.3 on 2025-07-16 13:52

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0009_alter_category_options'),
        ('structure', '0012_alter_governorate_head_alter_governorate_vice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('date', models.DateTimeField(verbose_name='تاريخ الفعالية')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة الفعالية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('quantity', models.IntegerField(verbose_name='عدد الاماكن')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.category', verbose_name='الفئات')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.governorate', verbose_name='المحافظة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_activities', to=settings.AUTH_USER_MODEL, verbose_name='تم التعديل بواسطة')),
            ],
            options={
                'verbose_name': 'النشاطات',
                'verbose_name_plural': 'النشاطات',
            },
        ),
    ]
