# Generated by Django 5.2.3 on 2025-07-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activities',
        ),
    ]
