# Generated by Django 5.2.3 on 2025-07-16 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('events', '0009_alter_category_options'),
        ('registrations', '0002_delete_activities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterationActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activities', verbose_name='النشاطات')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='مستخدم')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterationEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='العاليات')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='مستخدم')),
            ],
        ),
    ]
