# Generated by Django 5.2.3 on 2025-07-17 13:40

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('events', '0009_alter_category_options'),
        ('registrations', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerationactivities',
            options={'verbose_name': 'تسجيلات الأنشطة', 'verbose_name_plural': 'تسجيلات الأنشطة'},
        ),
        migrations.AlterModelOptions(
            name='registerationevents',
            options={'verbose_name': 'تسجيلات الفعاليات', 'verbose_name_plural': 'تسجيلات الفعاليات'},
        ),
        migrations.RemoveField(
            model_name='registerationactivities',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registerationevents',
            name='user',
        ),
        migrations.AlterField(
            model_name='registerationactivities',
            name='activities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activities', verbose_name='النشاط'),
        ),
        migrations.AlterField(
            model_name='registerationevents',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='الفعالية'),
        ),
        migrations.CreateModel(
            name='RegisterActivityUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, verbose_name='الرقم القومي')),
                ('id_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة الهوية')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.registerationactivities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='registerationactivities',
            name='users',
            field=models.ManyToManyField(related_name='activity_registrations', through='registrations.RegisterActivityUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RegisterEventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, verbose_name='الرقم القومي')),
                ('id_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة الهوية')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.registerationevents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='registerationevents',
            name='users',
            field=models.ManyToManyField(related_name='event_registrations', through='registrations.RegisterEventUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
