# Generated by Django 5.2.3 on 2025-07-17 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('events', '0009_alter_category_options'),
        ('registrations', '0004_alter_registerationactivities_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerationactivities',
            name='users',
        ),
        migrations.RemoveField(
            model_name='registereventuser',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='registereventuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registerationevents',
            name='users',
        ),
        migrations.AlterModelOptions(
            name='registerationactivities',
            options={'verbose_name': 'تسجيلات الانشطة', 'verbose_name_plural': 'تسجيلات الانشطة'},
        ),
        migrations.AlterModelOptions(
            name='registerationevents',
            options={'verbose_name': 'تسجيلات العاليات', 'verbose_name_plural': 'تسجيلات الفعاليات'},
        ),
        migrations.AddField(
            model_name='registerationactivities',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='مستخدم'),
        ),
        migrations.AddField(
            model_name='registerationevents',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='مستخدم'),
        ),
        migrations.AlterField(
            model_name='registerationactivities',
            name='activities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activities', verbose_name='النشاطات'),
        ),
        migrations.AlterField(
            model_name='registerationevents',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='العاليات'),
        ),
        migrations.DeleteModel(
            name='RegisterActivityUser',
        ),
        migrations.DeleteModel(
            name='RegisterEventUser',
        ),
    ]
