# Generated by Django 5.2.3 on 2025-07-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_branch_head_branch_vice_department_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governorate',
            name='location_link',
            field=models.URLField(blank=True, help_text='Paste Google Maps link like: https://www.google.com/maps/place/.../@30.12345,31.67890,17z', null=True),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
    ]
