# Generated by Django 5.2.3 on 2025-07-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_governorate_location_link_alter_governorate_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governorate',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
