# Generated by Django 5.2.3 on 2025-07-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_remove_department_governorate_remove_department_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralunit',
            name='name',
            field=models.CharField(choices=[('media', 'وحدة الإعلام المركزية'), ('org', 'وحدة التنظيم المركزي'), ('tech', 'وحدة البرمجة المركزية')], max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='CentralUnitMember',
        ),
    ]
