# Generated by Django 5.2.3 on 2025-07-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_alter_centralunit_name_delete_centralunitmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralunit',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
