# Generated by Django 5.2.3 on 2025-07-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_alter_centralunit_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centralunit',
            options={'verbose_name': 'الوحدة المركزية', 'verbose_name_plural': 'الوحدات المركزية'},
        ),
        migrations.AlterModelOptions(
            name='governorate',
            options={'verbose_name': 'محافظة', 'verbose_name_plural': 'المحافظات'},
        ),
    ]
