# Generated by Django 5.2.3 on 2025-07-10 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_alter_centralunit_options_alter_governorate_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centralunit',
            options={'verbose_name': 'وحدة مركزية', 'verbose_name_plural': 'الوحدات المركزية'},
        ),
        migrations.AlterField(
            model_name='centralunit',
            name='deputy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='central_deputy_of', to=settings.AUTH_USER_MODEL, verbose_name='نائب الرئيس'),
        ),
        migrations.AlterField(
            model_name='centralunit',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='central_head_of', to=settings.AUTH_USER_MODEL, verbose_name='رئيس الوحدة'),
        ),
        migrations.AlterField(
            model_name='centralunit',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم الوحدة'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='address',
            field=models.TextField(verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governorate_heads', to=settings.AUTH_USER_MODEL, verbose_name='رئيس المحافظة'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط العرض'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='location_link',
            field=models.URLField(blank=True, help_text='الصق رابط خرائط جوجل مثل: https://www.google.com/maps/place/.../@30.12345,31.67890,17z', null=True, verbose_name='رابط الموقع'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط الطول'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المحافظة'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='vice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governorate_vices', to=settings.AUTH_USER_MODEL, verbose_name='نائب الرئيس'),
        ),
    ]
