# Generated by Django 5.2.3 on 2025-07-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0009_alter_centralunit_options_alter_centralunit_deputy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centralunit',
            old_name='deputy',
            new_name='vice',
        ),
    ]
