# Generated by Django 5.2.3 on 2025-07-13 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_rename_deputy_centralunit_vice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralunit',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='central_head_of', to=settings.AUTH_USER_MODEL, verbose_name='رئيس الوحدة'),
        ),
        migrations.AlterField(
            model_name='centralunit',
            name='vice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='central_deputy_of', to=settings.AUTH_USER_MODEL, verbose_name='نائب الرئيس'),
        ),
    ]
