# Generated by Django 5.2.3 on 2025-07-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0012_alter_governorate_head_alter_governorate_vice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governorate',
            name='address',
        ),
        migrations.RemoveField(
            model_name='governorate',
            name='name',
        ),
        migrations.AddField(
            model_name='governorate',
            name='address_ar',
            field=models.TextField(default=1, verbose_name='العنوان بالعربي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='governorate',
            name='address_en',
            field=models.TextField(default=1, verbose_name='العنوان بالانجليزي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='governorate',
            name='name_ar',
            field=models.CharField(default=1, max_length=100, verbose_name='اسم المحافظة بالعربي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='governorate',
            name='name_en',
            field=models.CharField(default=1, max_length=100, verbose_name='اسم المحافظة بالانجليزي'),
            preserve_default=False,
        ),
    ]
